PapyrillioHgvBundle_DefaultIndex:
    pattern:  /start
    defaults: { _controller: PapyrillioHgvBundle:Default:index }

PapyrillioHgvBundle_DefaultAbbreviation:
    pattern:  /abbreviations
    defaults: { _controller: PapyrillioHgvBundle:Default:abbreviation }

PapyrillioHgvBundle_DefaultHelp:
    pattern:  /help/{topic}/{language}
    defaults: { _controller: PapyrillioHgvBundle:Default:help, topic: null, language: null }

PapyrillioHgvBundle_DefaultIntroduction:
    pattern:  /introduction
    defaults: { _controller: PapyrillioHgvBundle:Default:introduction }

PapyrillioHgvBundle_DefaultPublication:
    pattern:  /publicationList
    defaults: { _controller: PapyrillioHgvBundle:Default:publication }

PapyrillioHgvBundle_DefaultFeedback:
    pattern:  /feedback
    defaults: { _controller: PapyrillioHgvBundle:Default:feedback }

# P U B L I C A T I O N #

PapyrillioHgvBundle_PublicationLoadNumbers:
    pattern:  /publication/load/numbers/{collection}/{volume}/{particle}
    defaults: { _controller: PapyrillioHgvBundle:Publication:loadNumbers, collection: null, volume: null, particle: null }

PapyrillioHgvBundle_PublicationLoadResults:
    pattern:  /publication/load/results/{collection}/{volume}/{particle}/{number}/{side}/{extra}
    defaults: { _controller: PapyrillioHgvBundle:Publication:loadResults, collection: null, volume: null, particle: null, number: null, side: null, extra: null }
    requirements:
      particle: "[^/]*"
      number: "[^/]*"
      side: "[^/]*"

PapyrillioHgvBundle_PublicationIndex:
    pattern:  /publication
    defaults: { _controller: PapyrillioHgvBundle:Publication:index }

# B R O W S E #

PapyrillioHgvBundle_BrowseMultiple:
    pattern:  /
    defaults: { _controller: PapyrillioHgvBundle:Browse:multiple }

PapyrillioHgvBundle_BrowseSingle:
    pattern:  /show
    defaults: { _controller: PapyrillioHgvBundle:Browse:single }

PapyrillioHgvBundle_BrowseSearch:
    pattern:  /search
    defaults: { _controller: PapyrillioHgvBundle:Browse:search }

# S H O R T C U T #

PapyrillioHgvBundle_ShortcutHgv:
    pattern:  /hgv/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:hgv }
    requirements:
        id:  \d+[a-z]*

PapyrillioHgvBundle_ShortcutTm:
    pattern:  /tm/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:tm }
    requirements:
        id:  \d+

PapyrillioHgvBundle_ShortcutDdb:
    pattern:  /ddb/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:ddb }
    requirements:
        id:  "[^;]+;[^;]*;[^;]+"

PapyrillioHgvBundle_ShortcutDdbdp:
    pattern:  /ddb/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:ddb }
    requirements:
        id:  "([^;]+;[^;]*;[^;]*;[^;]+;[^;]*;[^;]*|[^;]+;[^;]*;[^;]+)" # Publikation, Band*, ZusBand*, Nummer, Seite*, zusaetzlich*
