PapyrillioHgvBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PapyrillioHgvBundle:Default:index }

# B R O W S E #

PapyrillioHgvBundle_BrowseMultiple:
    pattern:  /
    defaults: { _controller: PapyrillioHgvBundle:Browse:multiple }

PapyrillioHgvBundle_BrowseSingle:
    pattern:  /show
    defaults: { _controller: PapyrillioHgvBundle:Browse:single }

PapyrillioHgvBundle_BrowseSearch:
    pattern:  /search
    defaults: { _controller: PapyrillioHgvBundle:Browse:search }

# C A T A L O G U E #

PapyrillioHgvBundle_CatalogueList:
    pattern:  /list
    defaults: { _controller: PapyrillioHgvBundle:Catalogue:list }

PapyrillioHgvBundle_CatalogueShow:
    pattern:  /show
    defaults: { _controller: PapyrillioHgvBundle:Catalogue:show }

PapyrillioHgvBundle_CatalogueSearch:
    pattern:  /search
    defaults: { _controller: PapyrillioHgvBundle:Catalogue:search }

# S H O R T C U T #

PapyrillioHgvBundle_ShortcutHgv:
    pattern:  /hgv/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:hgv }
    requirements:
        id:  \d+[a-z]*

PapyrillioHgvBundle_ShortcutTm:
    pattern:  /tm/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:tm }
    requirements:
        id:  \d+

PapyrillioHgvBundle_ShortcutDdb:
    pattern:  /ddb/{id}
    defaults: { _controller: PapyrillioHgvBundle:Shortcut:ddb }
    requirements:
        id:  "[^;]+;[^;]*;[^;]+"
