# Language switch
app_switch_locale:
    path: /switch-locale/{locale}
    controller: App\Controller\LocaleController::switchLocale
    requirements:
        locale: de|en

# Import all application routes (no locale prefix)
app_routes:
    resource: routing/hgv.yaml
