Papyrillio\HgvBundle\Entity\MentionedDate:
    type: entity
    table: mentionedDate
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        jahr:
            type: integer
            nullable: true
        monat:
            type: integer
            nullable: true
        tag:
            type: integer
            nullable: true
        jh:
            type: integer
            nullable: true
        erg:
            type: text
            nullable: true
        jahrIi:
            name: jahr_ii
            type: integer
            nullable: true
        monatIi:
            name: monat_ii
            type: integer
            nullable: true
        tagIi:
            name: tag_ii
            type: integer
            nullable: true
        jhIi:
            name: jh_ii
            type: integer
            nullable: true
        ergIi:
            name: erg_ii
            type: text
            nullable: true
        unsicher:
            type: text
            nullable: true
        datierung:
            type: text
            nullable: true
        datierungIi:
            name: datierung_ii
            type: text
            nullable: true
        erwaehnteDaten:
            name: erwaehnte_daten
            type: text
            nullable: true
    manyToOne:
        metadata:
            targetEntity: Hgv
            joinColumn:
                name: texIdLang
                referencedColumnName: texIdLang
                type: string
                length: 64
                nullable: true

    # don't forget to init the collection in entity __construct() method