#!/usr/bin/env python3
"""Fill missing fr/en/it/es translations in data/keywords.csv based on the German column.

The CSV columns are: category, origin, de, fr, en, es, it.
Existing non-empty translations are preserved; only blank cells are filled.

The translations are intended for the HGV (Heidelberger Gesamtverzeichnis)
papyrological keyword vocabulary used in
TEI/teiHeader/profileDesc/textClass/keywords[@scheme='hgv']/term.
Many entries are Greek/Latin loanwords used as technical terms in papyrology
and are therefore kept as-is across all four target languages.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

# de -> (fr, en, it, es)
TRANSLATIONS: dict[str, tuple[str, str, str, str]] = {
    "Abgabe": ("Livraison", "Delivery", "Consegna", "Entrega"),
    "Abgaben": ("Livraisons", "Deliveries", "Consegne", "Entregas"),
    "Ablieferung von Wein": ("Livraison de vin", "Delivery of wine", "Consegna di vino", "Entrega de vino"),
    "Abrechnung": ("Décompte", "Settlement", "Conteggio", "Liquidación"),
    "Abrechnungen": ("Décomptes", "Settlements", "Conteggi", "Liquidaciones"),
    "Abrechung": ("Décompte", "Settlement", "Conteggio", "Liquidación"),
    "Abschrift": ("Copie", "Copy", "Copia", "Copia"),
    "Abschriften": ("Copies", "Copies", "Copie", "Copias"),
    "Abschriften von Briefen (amtlich)": ("Copies de lettres (officielles)", "Copies of letters (official)", "Copie di lettere (ufficiali)", "Copias de cartas (oficiales)"),
    "Abtretung": ("Cession", "Assignment", "Cessione", "Cesión"),
    "Achse": ("Axe", "Axis", "Asse", "Eje"),
    "Addition": ("Addition", "Addition", "Addizione", "Adición"),
    "Adresse": ("Adresse", "Address", "Indirizzo", "Dirección"),
    "Afterpacht": ("Sous-bail", "Sublease", "Subaffitto", "Subarriendo"),
    "Agriculteur": ("Agriculteur", "Farmer", "Agricoltore", "Agricultor"),
    "Akte": ("Dossier", "File", "Fascicolo", "Expediente"),
    "Akten": ("Dossiers", "Files", "Fascicoli", "Expedientes"),
    "Alexandria": ("Alexandrie", "Alexandria", "Alessandria", "Alejandría"),
    "Alimentation": ("Alimentation", "Alimony", "Alimenti", "Alimentos"),
    "Alphabet": ("Alphabet", "Alphabet", "Alfabeto", "Alfabeto"),
    "alphabetisch": ("alphabétique", "alphabetical", "alfabetico", "alfabético"),
    "Alter": ("Âge", "Age", "Età", "Edad"),
    "Alypios an Heroninos": ("Alypios à Héroninos", "Alypios to Heroninus", "Alypios a Heroninos", "Alypios a Heronino"),
    "Amir": ("Amir", "Amir", "Amir", "Amir"),
    "Amme": ("Nourrice", "Nurse", "Nutrice", "Nodriza"),
    "Ammon": ("Ammon", "Ammon", "Ammon", "Ammón"),
    "Amt": ("Charge", "Office", "Carica", "Cargo"),
    "amtlich": ("officiel", "official", "ufficiale", "oficial"),
    "Amtsmißbrauch": ("Abus de pouvoir", "Abuse of office", "Abuso d'ufficio", "Abuso de poder"),
    "Amulett": ("Amulette", "Amulet", "Amuleto", "Amuleto"),
    "Amyntas an Zenon": ("Amyntas à Zénon", "Amyntas to Zeno", "Amyntas a Zenone", "Amintas a Zenón"),
    "Anachoresis": ("Anachorèse", "Anachoresis", "Anacoresi", "Anacoresis"),
    "Anachoret": ("Anachorète", "Anchorite", "Anacoreta", "Anacoreta"),
    "Anagraphe": ("Anagraphè", "Anagraphe", "Anagraphe", "Anagraphe"),
    "andrismos": ("andrismos", "andrismos", "andrismos", "andrismos"),
    "Anerkenntnis": ("Reconnaissance", "Acknowledgement", "Riconoscimento", "Reconocimiento"),
    "Anfang": ("Début", "Beginning", "Inizio", "Comienzo"),
    "Anfrage": ("Demande", "Inquiry", "Richiesta", "Consulta"),
    "Angebot": ("Offre", "Offer", "Offerta", "Oferta"),
    "Angriff": ("Attaque", "Attack", "Attacco", "Ataque"),
    "Anklage": ("Accusation", "Accusation", "Accusa", "Acusación"),
    "Ankunft": ("Arrivée", "Arrival", "Arrivo", "Llegada"),
    "Anmeldung": ("Inscription", "Registration", "Iscrizione", "Inscripción"),
    "annona": ("annona", "annona", "annona", "annona"),
    "annona civica": ("annona civica", "annona civica", "annona civica", "annona civica"),
    "annona militaris": ("annona militaris", "annona militaris", "annona militaris", "annona militaris"),
    "Anordnung": ("Ordre", "Order", "Ordinanza", "Orden"),
    "Antichrese": ("Antichrèse", "Antichresis", "Anticresi", "Anticresis"),
    "Antigrapheus": ("Antigrapheus", "Antigrapheus", "Antigrapheus", "Antigrapheus"),
    "Antrag": ("Demande", "Application", "Domanda", "Solicitud"),
    "Antrag (Kauf, Land, Staat)": ("Demande (achat, terre, État)", "Application (purchase, land, state)", "Domanda (acquisto, terra, Stato)", "Solicitud (compra, tierra, Estado)"),
    "Antwort": ("Réponse", "Answer", "Risposta", "Respuesta"),
    "Anweisung": ("Instruction", "Instruction", "Istruzione", "Instrucción"),
    "Anweisung (Theon an den Ölmüller Sambas)": ("Instruction (Théon au meunier d'huile Sambas)", "Instruction (Theon to the oil miller Sambas)", "Istruzione (Teone al frantoiano Sambas)", "Instrucción (Teón al molinero de aceite Sambas)"),
    "Anweisungen": ("Instructions", "Instructions", "Istruzioni", "Instrucciones"),
    "Anzahl von Rollen (Garn?, Stoff?)": ("Nombre de rouleaux (fil?, étoffe?)", "Number of rolls (Yarn?, Fabric?)", "Numero di rotoli (filo?, tessuto?)", "Número de rollos (hilo?, tejido?)"),
    "Anzahlung": ("Acompte", "Down payment", "Acconto", "Pago inicial"),
    "Anzeige": ("Notification", "Advertisement", "Notifica", "Notificación"),
    "Apa Iohannes": ("Apa Iohannes", "Apa Iohannes", "Apa Iohannes", "Apa Iohannes"),
    "Aparche": ("Aparchè", "Aparche", "Aparche", "Aparche"),
    "ape": ("ape", "ape", "ape", "ape"),
    "Apographe": ("Apographè", "Apographe", "Apographe", "Apographe"),
    "Apollonios an Zenon": ("Apollonios à Zénon", "Apollonius to Zeno", "Apollonio a Zenone", "Apolonio a Zenón"),
    "Apomoira": ("Apomoira", "Apomoira", "Apomoira", "Apomoira"),
    "Araber": ("Arabes", "Arabs", "Arabi", "Árabes"),
    "Arakos": ("Arakos", "Arakos", "Arakos", "Arakos"),
    "Arbeit": ("Travail", "Work", "Lavoro", "Trabajo"),
    "Arbeiten": ("Travaux", "Works", "Lavori", "Trabajos"),
    "Arbeiter": ("Ouvrier", "Worker", "Operaio", "Trabajador"),
    "Archephodos": ("Archéphodos", "Archephodos", "Archephodos", "Archephodos"),
    "Architekt": ("Architecte", "Architect", "Architetto", "Arquitecto"),
    "Archiv": ("Archives", "Archive", "Archivio", "Archivo"),
    "Archives de Frangé": ("Archives de Frangé", "Archives de Frangé", "Archivi di Frangé", "Archivos de Frangé"),
    "Archonten": ("Archontes", "Archontes", "Arconti", "Arcontes"),
    "Argent": ("Argent", "Silver", "Argento", "Plata"),
    "Armee": ("Armée", "Army", "Esercito", "Ejército"),
    "Artaben": ("Artabes", "Artabai", "Artabe", "Artabas"),
    "Artemidoros an Zenon": ("Artémidoros à Zénon", "Artemidorus to Zeno", "Artemidoro a Zenone", "Artemidoro a Zenón"),
    "Aruren": ("Aroures", "Arurai", "Arure", "Aruras"),
    "Arzt": ("Médecin", "Physician", "Medico", "Médico"),
    "Asyl": ("Asile", "Asylum", "Asilo", "Asilo"),
    "Aufforderung": ("Sommation", "Request", "Sollecito", "Requerimiento"),
    "Aufschrift": ("Inscription", "Inscription", "Iscrizione", "Inscripción"),
    "Aufschrift auf Gefäßrest": ("Inscription sur fragment de récipient", "Inscription on vessel fragment", "Iscrizione su frammento di vaso", "Inscripción sobre fragmento de vasija"),
    "Aufschrift auf Gefäßverschluß": ("Inscription sur bouchon de récipient", "Inscription on vessel stopper", "Iscrizione su tappo di vaso", "Inscripción sobre tapón de vasija"),
    "Aufstellung": ("État", "Listing", "Elenco", "Listado"),
    "Aufteilung": ("Partage", "Division", "Divisione", "División"),
    "Aufteilung des Besitzes": ("Partage des biens", "Division of property", "Divisione dei beni", "División de los bienes"),
    "Auftrag": ("Commission", "Commission", "Incarico", "Encargo"),
    "Aufträge": ("Commissions", "Commissions", "Incarichi", "Encargos"),
    "Aufwendungen": ("Dépenses", "Expenditures", "Spese", "Gastos"),
    "Ausbildung": ("Formation", "Education", "Formazione", "Formación"),
    "Ausfuhr": ("Exportation", "Export", "Esportazione", "Exportación"),
    "Ausgabe": ("Délivrance", "Issuance", "Erogazione", "Emisión"),
    "Ausgabe von Beuteln": ("Délivrance de sacs", "Issuance of bags", "Erogazione di sacchetti", "Entrega de bolsas"),
    "Ausgabe von Wein": ("Délivrance de vin", "Issuance of wine", "Erogazione di vino", "Entrega de vino"),
    "Ausgabe von Werkzeug": ("Délivrance d'outil", "Issuance of Tool", "Erogazione di utensili", "Entrega de herramienta"),
    "Ausgaben": ("Dépenses", "Expenditures", "Spese", "Gastos"),
    "Ausrüstung": ("Équipement", "Equipment", "Equipaggiamento", "Equipo"),
    "Aussaat": ("Semailles", "Sowing", "Semina", "Siembra"),
    "Aussage": ("Déclaration", "Statement", "Dichiarazione", "Declaración"),
    "Auszahlung": ("Paiement", "Payment", "Pagamento", "Pago"),
    "Auszug": ("Extrait", "Extract", "Estratto", "Extracto"),
    "Auszüge": ("Extraits", "Extracts", "Estratti", "Extractos"),
    "Bäcker": ("Boulanger", "Baker", "Fornaio", "Panadero"),
    "Bäckerei": ("Boulangerie", "Bakery", "Panificio", "Panadería"),
    "Bad": ("Bain", "Bath", "Bagno", "Baño"),
    "Bäder": ("Bains", "Baths", "Bagni", "Baños"),
    "Badesteuer": ("Impôt sur les bains", "Bath tax", "Tassa sui bagni", "Impuesto sobre los baños"),
    "Bandelettes": ("Bandelettes", "Bandelettes", "Bende", "Vendas"),
    "Bank": ("Banque", "Bank", "Banca", "Banco"),
    "Bankier": ("Banquier", "Banker", "Banchiere", "Banquero"),
    "Bau": ("Construction", "Construction", "Costruzione", "Construcción"),
    "Bauarbeiten": ("Travaux de construction", "Construction work", "Lavori di costruzione", "Obras de construcción"),
    "Bauer": ("Paysan", "Farmer", "Contadino", "Campesino"),
    "Bauern": ("Paysans", "Farmers", "Contadini", "Campesinos"),
    "Bauland": ("Terrain à bâtir", "Building land", "Terreno edificabile", "Solar"),
    "Baum": ("Arbre", "Tree", "Albero", "Árbol"),
    "Baumaterial": ("Matériau de construction", "Building material", "Materiale da costruzione", "Material de construcción"),
    "Bäume": ("Arbres", "Trees", "Alberi", "Árboles"),
    "Baumwolle": ("Coton", "Cotton", "Cotone", "Algodón"),
    "Beamte": ("Fonctionnaires", "Officials", "Funzionari", "Funcionarios"),
    "Beamter": ("Fonctionnaire", "Civil servants", "Funzionario", "Funcionario"),
    "Bearbeitung": ("Traitement", "Processing", "Trattamento", "Procesamiento"),
    "Bebauung": ("Mise en culture", "Development", "Coltivazione", "Cultivo"),
    "Bedienstete": ("Personnel", "Employees", "Personale", "Empleados"),
    "Befehl": ("Ordre", "Order", "Ordine", "Orden"),
    "Befreiung": ("Exemption", "Exemption", "Esenzione", "Exención"),
    "Begleitbrief": ("Lettre d'accompagnement", "Accompanying letter", "Lettera d'accompagnamento", "Carta de acompañamiento"),
    "Begleitschreiben": ("Lettre d'accompagnement", "Cover letter", "Lettera di accompagnamento", "Carta de presentación"),
    "Beleg": ("Reçu", "Receipt", "Ricevuta", "Recibo"),
    "Berechnung": ("Calcul", "Calculation", "Calcolo", "Cálculo"),
    "Berechnungen": ("Calculs", "Calculations", "Calcoli", "Cálculos"),
    "Bereitstellung": ("Mise à disposition", "Provision", "Fornitura", "Provisión"),
    "Bericht": ("Rapport", "Report", "Rapporto", "Informe"),
    "Beruf": ("Profession", "Profession", "Professione", "Profesión"),
    "Berufe": ("Professions", "Professions", "Professioni", "Profesiones"),
    "Berufsgruppen": ("Catégories professionnelles", "Occupational groups", "Categorie professionali", "Grupos profesionales"),
    "Bescheinigung": ("Reçu", "Certificate", "Certificato", "Certificado"),
    "Beschlagnahme": ("Saisie", "Seizure", "Sequestro", "Confiscación"),
    "Beschreibung": ("Description", "Description", "Descrizione", "Descripción"),
    "Beschwerde": ("Plainte", "Complaint", "Reclamo", "Queja"),
    "Besitz": ("Propriété", "Possession", "Possesso", "Posesión"),
    "Besitzer": ("Propriétaire", "Owner", "Proprietario", "Propietario"),
    "Bestand": ("Inventaire", "Inventory", "Inventario", "Inventario"),
    "Bestätigung": ("Confirmation", "Confirmation", "Conferma", "Confirmación"),
    "Bestattung": ("Funérailles", "Burial", "Sepoltura", "Entierro"),
    "Bestellung": ("Commande", "Order", "Ordine", "Pedido"),
    "Bestimmungsort": ("Destination", "Destination", "Destinazione", "Destino"),
    "Besuch": ("Visite", "Visit", "Visita", "Visita"),
    "Besucher": ("Visiteur", "Visitor", "Visitatore", "Visitante"),
    "Beträge": ("Montants", "Amounts", "Importi", "Importes"),
    "Betrug": ("Fraude", "Fraud", "Frode", "Fraude"),
    "Bewachung": ("Garde", "Guarding", "Sorveglianza", "Vigilancia"),
    "Bewässerung": ("Irrigation", "Irrigation", "Irrigazione", "Irrigación"),
    "Bezahlung": ("Paiement", "Payment", "Pagamento", "Pago"),
    "Bier": ("Bière", "Beer", "Birra", "Cerveza"),
    "Billet": ("Billet", "Bill", "Biglietto", "Boleto"),
    "Bischof": ("Évêque", "Bishop", "Vescovo", "Obispo"),
    "Bitte": ("Demande", "Request", "Richiesta", "Petición"),
    "Bitte um Antwort": ("Demande de réponse", "Request a reply", "Richiesta di risposta", "Solicitud de respuesta"),
    "Bitte um Hilfe": ("Demande d'aide", "Request for Help", "Richiesta di aiuto", "Solicitud de ayuda"),
    "Bittschrift": ("Pétition", "Petition", "Petizione", "Petición"),
    "Blé": ("Blé", "Wheat", "Grano", "Trigo"),
    "Blei": ("Plomb", "Lead", "Piombo", "Plomo"),
    "Boden": ("Sol", "Soil", "Suolo", "Suelo"),
    "Bohnen": ("Fèves", "Beans", "Fave", "Habas"),
    "Boot": ("Bateau", "Boat", "Barca", "Bote"),
    "Brief": ("Lettre", "Letter", "Lettera", "Carta"),
    "Briefe": ("Lettres", "Letters", "Lettere", "Cartas"),
    "Briefträger": ("Facteur", "Postman", "Postino", "Cartero"),
    "Brot": ("Pain", "Bread", "Pane", "Pan"),
    "Brote": ("Pains", "Loaves of bread", "Pagnotte", "Hogazas"),
    "Brunnen": ("Puits", "Well", "Pozzo", "Pozo"),
    "Buch": ("Livre", "Book", "Libro", "Libro"),
    "Bücher": ("Livres", "Books", "Libri", "Libros"),
    "Buchstaben": ("Lettres", "Letters", "Lettere", "Letras"),
    "Bürge": ("Garant", "Guarantor", "Garante", "Garante"),
    "Bürgen": ("Garants", "Guarantors", "Garanti", "Garantes"),
    "Bürgschaft": ("Caution", "Guarantee", "Garanzia", "Fianza"),
    "Centurie": ("Centurie", "Centurie", "Centuria", "Centuria"),
    "Chrematisten": ("Chrématistes", "Chrematists", "Chrematisti", "Crematistas"),
    "christlich": ("chrétien", "Christian", "cristiano", "cristiano"),
    "Damm": ("Digue", "Dam", "Diga", "Presa"),
    "Darlehen": ("Prêt en argent", "Loan", "Prestito", "Préstamo"),
    "Daten": ("Données", "Data", "Dati", "Datos"),
    "Datierung": ("Datation", "Dating", "Datazione", "Datación"),
    "Datteln": ("Dattes", "Dates", "Datteri", "Dátiles"),
    "Datum": ("Date", "Date", "Data", "Fecha"),
    "Dauer": ("Durée", "Duration", "Durata", "Duración"),
    "Deich": ("Digue", "Dike", "Diga", "Dique"),
    "Deicharbeiten": ("Travaux de digue", "Dike work", "Lavori di diga", "Obras de dique"),
    "Deichsteuer": ("Impôt sur les digues", "Dike tax", "Tassa sulle dighe", "Impuesto sobre los diques"),
    "dekania": ("dékania", "Decania", "decania", "decania"),
    "Dekaproten": ("Décaprotes", "Decaprotes", "Decaproti", "Decaprotos"),
    "Deklaration": ("Déclaration", "Declaration", "Dichiarazione", "Declaración"),
    "Demande d’envoi": ("Demande d’envoi", "Request for delivery", "Richiesta di invio", "Solicitud de envío"),
    "Demande de rencontre": ("Demande de rencontre", "Request for meeting", "Richiesta di incontro", "Solicitud de reunión"),
    "Demetrios an Zenon": ("Démétrios à Zénon", "Demetrios to Zeno", "Demetrio a Zenone", "Demetrio a Zenón"),
    "demotisch": ("démotique", "Demotic", "demotico", "demótico"),
    "demotische Verträge": ("contrats démotiques", "Demotic contracts", "contratti demotici", "contratos demóticos"),
    "den Lagerort einer Lieferung festzustellen und zu bestätigen": ("établir et confirmer le lieu de stockage d'une livraison", "to establish and confirm the location of a shipment", "accertare e confermare il luogo di deposito di una consegna", "establecer y confirmar el lugar de almacenamiento de un envío"),
    "der Eklogistes Zoilos an den Strategen Domittios Diosarapis alias Balbillos": ("de l'éclogiste Zoïlos au stratège Domittios Diosarapis alias Balbillos", "of the eclogist Zoilos to the strategos Domittius Diosarapis alias Balbillus", "dell'eclogista Zoilo al stratego Domizio Diosarapide detto Balbillo", "del eclogista Zoilo al estratega Domicio Diosarapis alias Balbilo"),
    "des Dioiketen Septimius Arrianus": ("du dioecète Septimius Arrianus", "of the Dioicetes Septimius Arrianus", "del dieceto Settimio Arriano", "del dioiketes Septimio Arriano"),
    "Diagraphe": ("Diagraphè", "Diagraphe", "Diagraphe", "Diagraphe"),
    "diagraphon": ("diagraphon", "Diagraphon", "diagraphon", "diagraphon"),
    "Diakon": ("Diacre", "Deacon", "Diacono", "Diácono"),
    "Dialysis": ("Dialysis", "Dialysis", "Dialysis", "Dialysis"),
    "Diebstahl": ("Vol", "Theft", "Furto", "Robo"),
    "Dienst": ("Service", "Service", "Servizio", "Servicio"),
    "Dienstweg": ("Voie hiérarchique", "Channel", "Via gerarchica", "Vía jerárquica"),
    "Dioiket": ("Dioecète", "Dioiket", "Dieceto", "Dioiketes"),
    "Dioiketes": ("Dioecète", "Dioiketes", "Dieceto", "Dioiketes"),
    "Document": ("Document", "Document", "Documento", "Documento"),
    "Dokument": ("Document", "Document", "Documento", "Documento"),
    "Dokumente": ("Documents", "Documents", "Documenti", "Documentos"),
    "Domäne": ("Domaine", "Domain", "Dominio", "Dominio"),
    "doppelte Ausfertigung": ("double exemplaire", "Duplicate copy", "doppia copia", "doble ejemplar"),
    "Doppelurkunde": ("acte double", "Duplicate deed", "atto doppio", "escritura doble"),
    "Dorf": ("Village", "Village", "Villaggio", "Aldea"),
    "Dörfer": ("Villages", "Villages", "Villaggi", "Aldeas"),
    "Dorfschreiber": ("Scribe de village", "Village clerk", "Scriba di villaggio", "Escriba del pueblo"),
    "Dorfschreiber Petaus an den Strategen Apollonios": ("Scribe de village Pétaus au stratège Apollonios", "Village clerk Petaus to the strategos Apollonius", "Scriba di villaggio Petaus al stratego Apollonio", "Escriba del pueblo Petaus al estratega Apolonio"),
    "Dorfvorsteher": ("Chef de village", "Village leader", "Capovillaggio", "Jefe de aldea"),
    "Drachmen": ("Drachmes", "Drachmas", "Dracme", "Dracmas"),
    "Drohung": ("Menace", "Threat", "Minaccia", "Amenaza"),
    "Edikt": ("Édit", "Edict", "Editto", "Edicto"),
    "Ehe": ("Mariage", "Marriage", "Matrimonio", "Matrimonio"),
    "Eid": ("Serment", "Oath", "Giuramento", "Juramento"),
    "Eier": ("Œufs", "Eggs", "Uova", "Huevos"),
    "Eigentum": ("Propriété", "Property", "Proprietà", "Propiedad"),
    "Einbruch": ("Effraction", "Burglary", "Effrazione", "Robo con allanamiento"),
    "Eingabe": ("Requête", "Petition", "Istanza", "Instancia"),
    "Eingabe an den Phrurarchen": ("Requête au phrourarque", "Petition to the phrourarch", "Istanza al frurarca", "Instancia al frurarca"),
    "Eingabe an den Präfekten": ("Requête au préfet", "Petition to the prefect", "Istanza al prefetto", "Instancia al prefecto"),
    "Eingabe an den Strategen": ("Requête au stratège", "Petition to the strategos", "Istanza al stratego", "Instancia al estratega"),
    "Eingaben": ("Requêtes", "Petitions", "Istanze", "Instancias"),
    "Einkünfte": ("Revenus", "Income", "Entrate", "Ingresos"),
    "Einladung": ("Invitation", "Invitation", "Invito", "Invitación"),
    "Einnahme": ("Recette", "Revenue", "Entrata", "Ingreso"),
    "Einnahmen": ("Recettes", "Revenues", "Entrate", "Ingresos"),
    "Einnahmen und Ausgaben": ("Recettes et dépenses", "Income and expenditure", "Entrate e uscite", "Ingresos y gastos"),
    "Einsatzort": ("Lieu d'affectation", "Place of duty", "Luogo di servizio", "Lugar de destino"),
    "Eintragung": ("Inscription", "Entry", "Registrazione", "Registro"),
    "Eintreibung": ("Recouvrement", "Collection", "Riscossione", "Recaudación"),
    "Einwohner": ("Habitants", "Inhabitants", "Abitanti", "Habitantes"),
    "Einziehung": ("Recouvrement", "Collection", "Riscossione", "Recaudación"),
    "Eisen": ("Fer", "Iron", "Ferro", "Hierro"),
    "Embole": ("Embolè", "Embole", "Embole", "Embole"),
    "Empfang": ("Réception", "Receipt", "Ricevimento", "Recepción"),
    "Empfang eines Ersatzteils einer Maschine (Bewässerung)": ("Réception d'une pièce de rechange d'une machine (irrigation)", "Receipt of a spare part for a machine (irrigation)", "Ricevimento di un pezzo di ricambio di una macchina (irrigazione)", "Recepción de una pieza de repuesto de una máquina (irrigación)"),
    "Empfang von Wein": ("Réception de vin", "Receipt of wine", "Ricevimento di vino", "Recepción de vino"),
    "Empfänger": ("Destinataire", "Recipient", "Destinatario", "Destinatario"),
    "Empfehlung": ("Recommandation", "Recommendation", "Raccomandazione", "Recomendación"),
    "Empfehlungsschreiben": ("Lettre de recommandation", "Letter of recommendation", "Lettera di raccomandazione", "Carta de recomendación"),
    "Ende": ("Fin", "End", "Fine", "Fin"),
    "Entagion": ("Entagion", "Entagion", "Entagion", "Entagion"),
    "Enteuxis": ("Enteuxis", "Enteuxis", "Enteuxis", "Enteuxis"),
    "Entlassung": ("Licenciement", "Dismissal", "Licenziamento", "Despido"),
    "Entwurf": ("Brouillon", "Draft", "Bozza", "Borrador"),
    "Envoi": ("Envoi", "Shipment", "Invio", "Envío"),
    "epibole didrachmu": ("epibole didrachmu", "epibole didrachmu", "epibole didrachmu", "epibole didrachmu"),
    "Epikrisis": ("Épicrisis", "Epicrisis", "Epicrisi", "Epicrisis"),
    "Episkepsis": ("Épiskepsis", "Episkepsis", "Episkepsis", "Episkepsis"),
    "epistates phylakiton": ("epistates phylakiton", "epistates phylakiton", "epistates phylakiton", "epistates phylakiton"),
    "Epistratege": ("Épistratège", "Epistrategos", "Epistratego", "Epistratego"),
    "Erbe": ("Héritier", "Heir", "Erede", "Heredero"),
    "Erben": ("Héritiers", "Heirs", "Eredi", "Herederos"),
    "Erbschaft": ("Héritage", "Inheritance", "Eredità", "Herencia"),
    "Erhalt": ("Réception", "Receipt", "Ricevimento", "Recepción"),
    "Erhebung": ("Perception", "Levy", "Riscossione", "Recaudación"),
    "Erklärung": ("Déclaration", "Declaration", "Dichiarazione", "Declaración"),
    "Erlaß": ("Édit", "Decree", "Decreto", "Decreto"),
    "Erlaubnis": ("Permission", "Permission", "Permesso", "Permiso"),
    "Ernennung": ("Nomination", "Appointment", "Nomina", "Nombramiento"),
    "Ernte": ("Récolte", "Harvest", "Raccolto", "Cosecha"),
    "Ertrag": ("Rendement", "Yield", "Rendita", "Rendimiento"),
    "Erven": ("Vesces", "Vetches", "Vecce", "Vezas"),
    "Esel": ("Âne", "Donkey", "Asino", "Burro"),
    "Eselin": ("Ânesse", "She-donkey", "Asina", "Burra"),
    "Eseltreiber": ("Ânier", "Donkey driver", "Asinaio", "Burrero"),
    "Essen": ("Repas", "Food", "Cibo", "Comida"),
    "Essig": ("Vinaigre", "Vinegar", "Aceto", "Vinagre"),
    "Exercice": ("Exercice", "Exercise", "Esercizio", "Ejercicio"),
    "Exercice épistolaire": ("Exercice épistolaire", "Epistolary exercise", "Esercizio epistolare", "Ejercicio epistolar"),
    "Familie": ("Famille", "Family", "Famiglia", "Familia"),
    "Farben": ("Couleurs", "Colours", "Colori", "Colores"),
    "Färber": ("Teinturier", "Dyer", "Tintore", "Tintorero"),
    "Fässer": ("Tonneaux", "Barrels", "Botti", "Barriles"),
    "Feld": ("Champ", "Field", "Campo", "Campo"),
    "Feldfrüchte": ("Récoltes", "Crops", "Raccolti", "Cultivos"),
    "Felle": ("Peaux", "Hides", "Pelli", "Pieles"),
    "Femme": ("Femme", "Woman", "Donna", "Mujer"),
    "Femmes": ("Femmes", "Women", "Donne", "Mujeres"),
    "Ferkel": ("Porcelet", "Piglet", "Maialino", "Lechón"),
    "Fest": ("Fête", "Festival", "Festa", "Fiesta"),
    "Festnahme": ("Arrestation", "Arrest", "Arresto", "Detención"),
    "Fisch": ("Poisson", "Fish", "Pesce", "Pez"),
    "Fische": ("Poissons", "Fish", "Pesci", "Peces"),
    "Fischer": ("Pêcheur", "Fisherman", "Pescatore", "Pescador"),
    "Fischerei": ("Pêche", "Fishing", "Pesca", "Pesca"),
    "Fiskus": ("Fisc", "Treasury", "Fisco", "Fisco"),
    "Flachs": ("Lin", "Flax", "Lino", "Lino"),
    "Fleisch": ("Viande", "Meat", "Carne", "Carne"),
    "Flotte": ("Flotte", "Fleet", "Flotta", "Flota"),
    "Flucht": ("Fuite", "Flight", "Fuga", "Huida"),
    "Flüchtlinge": ("Fugitifs", "Fugitives", "Fuggiaschi", "Fugitivos"),
    "Fohlen": ("Poulain", "Foal", "Puledro", "Potro"),
    "Forderung": ("Créance", "Claim", "Pretesa", "Reclamación"),
    "Formeln": ("Formules", "Formulas", "Formule", "Fórmulas"),
    "Fracht": ("Fret", "Freight", "Nolo", "Flete"),
    "Frachtkosten": ("Frais de transport", "Freight costs", "Spese di trasporto", "Costes de transporte"),
    "Frage": ("Question", "Question", "Domanda", "Pregunta"),
    "Fragment": ("Fragment", "Fragment", "Frammento", "Fragmento"),
    "fragmentarisch": ("fragmentaire", "fragmentary", "frammentario", "fragmentario"),
    "Fragmente": ("Fragments", "Fragments", "Frammenti", "Fragmentos"),
    "Frau": ("Femme", "Woman", "Donna", "Mujer"),
    "Frauen": ("Femmes", "Women", "Donne", "Mujeres"),
    "Freigelassener": ("Affranchi", "Freedman", "Liberto", "Liberto"),
    "Freilassung": ("Affranchissement", "Manumission", "Manomissione", "Manumisión"),
    "Frist": ("Délai", "Deadline", "Termine", "Plazo"),
    "fünf Tage": ("cinq jours", "five days", "cinque giorni", "cinco días"),
    "Futter": ("Fourrage", "Fodder", "Foraggio", "Forraje"),
    "Garantie": ("Garantie", "Guarantee", "Garanzia", "Garantía"),
    "Garten": ("Jardin", "Garden", "Giardino", "Jardín"),
    "Gebäude": ("Bâtiment", "Building", "Edificio", "Edificio"),
    "Gebet": ("Prière", "Prayer", "Preghiera", "Oración"),
    "Gebühr": ("Taxe", "Fee", "Tassa", "Tasa"),
    "Gebühren": ("Taxes", "Fees", "Tasse", "Tasas"),
    "Geburt": ("Naissance", "Birth", "Nascita", "Nacimiento"),
    "Geburtsdatum": ("Date de naissance", "Date of birth", "Data di nascita", "Fecha de nacimiento"),
    "Gefangene": ("Prisonniers", "Prisoners", "Prigionieri", "Prisioneros"),
    "Gefängnis": ("Prison", "Prison", "Prigione", "Prisión"),
    "Gefäß": ("Récipient", "Vessel", "Recipiente", "Recipiente"),
    "Gefäße": ("Récipients", "Vessels", "Recipienti", "Recipientes"),
    "Geflügel": ("Volaille", "Poultry", "Pollame", "Aves de corral"),
    "Gegenstände": ("Objets", "Objects", "Oggetti", "Objetos"),
    "Gehalt": ("Salaire", "Salary", "Stipendio", "Salario"),
    "Geld": ("Argent", "Money", "Denaro", "Dinero"),
    "Geldbetrag": ("Somme d'argent", "Amount of money", "Somma di denaro", "Suma de dinero"),
    "Geldbeträge": ("Sommes d'argent", "Amounts of money", "Somme di denaro", "Sumas de dinero"),
    "Gemüse": ("Légumes", "Vegetables", "Verdure", "Verduras"),
    "Gemüsesamen": ("Graines de légumes", "Vegetable seeds", "Semi di verdura", "Semillas de verdura"),
    "geometria": ("geometria", "geometria", "geometria", "geometria"),
    "Geräte": ("Outils", "Tools", "Attrezzi", "Herramientas"),
    "Gericht": ("Tribunal", "Court", "Tribunale", "Tribunal"),
    "Gerste": ("Orge", "Barley", "Orzo", "Cebada"),
    "Geschäft": ("Affaire", "Business", "Affare", "Negocio"),
    "Geschäfte": ("Affaires", "Businesses", "Affari", "Negocios"),
    "geschäftlich": ("commercial", "business", "commerciale", "comercial"),
    "Geschäftliches": ("Affaires commerciales", "Business matters", "Questioni commerciali", "Asuntos comerciales"),
    "Geschenke": ("Cadeaux", "Gifts", "Regali", "Regalos"),
    "Gesetz": ("Loi", "Law", "Legge", "Ley"),
    "Gestellung": ("Mise à disposition", "Provision", "Messa a disposizione", "Provisión"),
    "Gesuch": ("Requête", "Petition", "Istanza", "Petición"),
    "Gesundheit": ("Santé", "Health", "Salute", "Salud"),
    "Getreide": ("Céréales", "Grain", "Grano", "Grano"),
    "Gewalt": ("Violence", "Violence", "Violenza", "Violencia"),
    "Gewerbe": ("Métier", "Trade", "Mestiere", "Oficio"),
    "Gewicht": ("Poids", "Weight", "Peso", "Peso"),
    "Gilde": ("Corporation", "Guild", "Corporazione", "Gremio"),
    "Giro - Überweisung von Weizen": ("Virement de blé", "Transfer of wheat", "Bonifico di grano", "Transferencia de trigo"),
    "Gold": ("Or", "Gold", "Oro", "Oro"),
    "Grabinschrift": ("Inscription funéraire", "Tomb inscription", "Iscrizione funeraria", "Inscripción funeraria"),
    "Graffito": ("Graffite", "Graffito", "Graffito", "Grafito"),
    "Graffitto": ("Graffite", "Graffito", "Graffito", "Grafito"),
    "Grapheion": ("Grapheion", "Grapheion", "Grapheion", "Grapheion"),
    "Griechische Beischrift zu demotischer Urkunde": ("Souscription grecque à un document démotique", "Greek subscription to demotic document", "Sottoscrizione greca a documento demotico", "Suscripción griega a documento demótico"),
    "griechische Unterschrift": ("signature grecque", "Greek signature", "firma greca", "firma griega"),
    "griechisches Protokoll und Unterschrift": ("protocole et signature en grec", "Greek protocol and signature", "protocollo e firma in greco", "protocolo y firma en griego"),
    "Grundbesitz": ("Propriété foncière", "Landed property", "Proprietà fondiaria", "Propiedad inmobiliaria"),
    "Grundbuch": ("Cadastre", "Land register", "Catasto", "Catastro"),
    "Grundbuchamt": ("Bureau du cadastre", "Land registry office", "Ufficio catastale", "Oficina catastral"),
    "Grundstück": ("Terrain", "Plot of land", "Terreno", "Terreno"),
    "Grundstücke": ("Terrains", "Plots of land", "Terreni", "Terrenos"),
    "Grünfutter": ("Fourrage vert", "Green fodder", "Foraggio verde", "Forraje verde"),
    "Gruß": ("Salutation", "Greeting", "Saluto", "Saludo"),
    "Grüße": ("Salutations", "Greetings", "Saluti", "Saludos"),
    "Gut": ("Domaine", "Estate", "Tenuta", "Finca"),
    "Gutachten": ("Expertise", "Expert opinion", "Perizia", "Dictamen"),
    "Güter": ("Biens", "Goods", "Beni", "Bienes"),
    "Gymnasion": ("Gymnase", "Gymnasion", "Ginnasio", "Gimnasio"),
    "Gymnasium": ("Gymnase", "Gymnasium", "Ginnasio", "Gimnasio"),
    "Hafen": ("Port", "Harbour", "Porto", "Puerto"),
    "Haft": ("Détention", "Custody", "Detenzione", "Detención"),
    "Handel": ("Commerce", "Trade", "Commercio", "Comercio"),
    "Händler": ("Marchand", "Merchant", "Mercante", "Comerciante"),
    "Handwerk": ("Artisanat", "Craft", "Artigianato", "Artesanía"),
    "Handwerker": ("Artisan", "Craftsman", "Artigiano", "Artesano"),
    "Haus": ("Maison", "House", "Casa", "Casa"),
    "Häuser": ("Maisons", "Houses", "Case", "Casas"),
    "Haushalt": ("Ménage", "Household", "Famiglia", "Hogar"),
    "Haushalte": ("Ménages", "Households", "Famiglie", "Hogares"),
    "Heer": ("Armée", "Army", "Esercito", "Ejército"),
    "Heiligtum": ("Sanctuaire", "Sanctuary", "Santuario", "Santuario"),
    "Heirat": ("Mariage", "Marriage", "Matrimonio", "Matrimonio"),
    "Herkunft": ("Origine", "Origin", "Origine", "Origen"),
    "Herstellung": ("Fabrication", "Manufacture", "Produzione", "Fabricación"),
    "Heu": ("Foin", "Hay", "Fieno", "Heno"),
    "Hierokles an Zenon": ("Hiéroklès à Zénon", "Hierokles to Zeno", "Ierocle a Zenone", "Hierocles a Zenón"),
    "Hilfe": ("Aide", "Help", "Aiuto", "Ayuda"),
    "Hirte": ("Berger", "Shepherd", "Pastore", "Pastor"),
    "Hirten": ("Bergers", "Shepherds", "Pastori", "Pastores"),
    "Hochzeit": ("Mariage", "Wedding", "Nozze", "Boda"),
    "Hof": ("Cour", "Courtyard", "Cortile", "Patio"),
    "Holz": ("Bois", "Wood", "Legno", "Madera"),
    "Homologie": ("Homologie", "Homology", "Omologia", "Homología"),
    "Honig": ("Miel", "Honey", "Miele", "Miel"),
    "Horion an Heroninos": ("Horion à Héroninos", "Horion to Heroninus", "Horion a Heroninos", "Horion a Heronino"),
    "Horoskop": ("Horoscope", "Horoscope", "Oroscopo", "Horóscopo"),
    "Huhn": ("Poule", "Hen", "Gallina", "Gallina"),
    "Hühner": ("Poules", "Hens", "Galline", "Gallinas"),
    "Huile": ("Huile", "Oil", "Olio", "Aceite"),
    "Hülsenfrüchte": ("Légumineuses", "Legumes", "Legumi", "Legumbres"),
    "Hunger": ("Famine", "Hunger", "Fame", "Hambre"),
    "Hypallagma": ("Hypallagma", "Hypallagma", "Hypallagma", "Hypallagma"),
    "Hypodektes": ("Hypodektes", "Hypodektes", "Hypodektes", "Hypodektes"),
    "Hypographe": ("Hypographè", "Hypographe", "Hypographe", "Hypographe"),
    "Hypomnema": ("Hypomnema", "Hypomnema", "Hypomnema", "Hypomnema"),
    "Hypothek": ("Hypothèque", "Mortgage", "Ipoteca", "Hipoteca"),
    "Idioslogos": ("Idiologue", "Idioslogos", "Idiologo", "Idiólogo"),
    "Immobilien": ("Biens immobiliers", "Real estate", "Beni immobili", "Bienes inmuebles"),
    "Inhalt": ("Contenu", "Content", "Contenuto", "Contenido"),
    "Inhalt unbestimmbar": ("Contenu indéterminable", "Content indeterminable", "Contenuto indeterminabile", "Contenido indeterminable"),
    "Inschrift": ("Inscription", "Inscription", "Iscrizione", "Inscripción"),
    "Inspektion": ("Inspection", "Inspection", "Ispezione", "Inspección"),
    "Inventar": ("Inventaire", "Inventory", "Inventario", "Inventario"),
    "Invocatio": ("Invocatio", "Invocatio", "Invocatio", "Invocatio"),
    "Invokation": ("Invocation", "Invocation", "Invocazione", "Invocación"),
    "Ischyras an Parabolos": ("Ischyras à Parabolos", "Ischyras to Parabolos", "Ischyras a Parabolos", "Ischyras a Parabolos"),
    "Ischyrion an Heroninos": ("Ischyrion à Héroninos", "Ischyrion to Heroninus", "Ischyrion a Heroninos", "Ischyrion a Heronino"),
    "Juden": ("Juifs", "Jews", "Ebrei", "Judíos"),
    "Kaiser": ("Empereur", "Emperor", "Imperatore", "Emperador"),
    "Kaisereid": ("Serment impérial", "Imperial oath", "Giuramento imperiale", "Juramento imperial"),
    "Kalb": ("Veau", "Calf", "Vitello", "Ternero"),
    "Kälber": ("Veaux", "Calves", "Vitelli", "Terneros"),
    "Kalender": ("Calendrier", "Calendar", "Calendario", "Calendario"),
    "Kamel": ("Chameau", "Camel", "Cammello", "Camello"),
    "Kamele": ("Chameaux", "Camels", "Cammelli", "Camellos"),
    "Kameltreiber": ("Chamelier", "Camel driver", "Cammelliere", "Camellero"),
    "Kanal": ("Canal", "Canal", "Canale", "Canal"),
    "Käse": ("Fromage", "Cheese", "Formaggio", "Queso"),
    "Kataster": ("Cadastre", "Cadastre", "Catasto", "Catastro"),
    "Katöken": ("Catèques", "Catoeci", "Catechi", "Catecos"),
    "Katökenland": ("Terre catécique", "Catoecic land", "Terra catechica", "Tierra cateca"),
    "Kauf": ("Achat", "Purchase", "Acquisto", "Compra"),
    "Käufe": ("Achats", "Purchases", "Acquisti", "Compras"),
    "Kaufpreis": ("Prix d'achat", "Purchase price", "Prezzo d'acquisto", "Precio de compra"),
    "Kerkeosiris": ("Kerkéosiris", "Kerkeosiris", "Kerkeosiris", "Kerkeosiris"),
    "Kind": ("Enfant", "Child", "Bambino", "Niño"),
    "Kinder": ("Enfants", "Children", "Bambini", "Niños"),
    "Kirche": ("Église", "Church", "Chiesa", "Iglesia"),
    "Klage": ("Plainte", "Complaint", "Querela", "Demanda"),
    "Klassifizierung": ("Classification", "Classification", "Classificazione", "Clasificación"),
    "Klauseln": ("Clauses", "Clauses", "Clausole", "Cláusulas"),
    "Kleider": ("Vêtements", "Clothes", "Vestiti", "Ropa"),
    "Kleidung": ("Vêtement", "Clothing", "Abbigliamento", "Vestimenta"),
    "Kleidungsstücke": ("Vêtements", "Garments", "Capi di abbigliamento", "Prendas de vestir"),
    "Kleinvieh": ("Petit bétail", "Small livestock", "Bestiame minuto", "Ganado menor"),
    "Kleros": ("Klèros", "Kleros", "Kleros", "Kleros"),
    "Kleruche": ("Cléruque", "Cleruch", "Cleruco", "Cleruco"),
    "Kleruchen": ("Cléruques", "Cleruchs", "Cleruchi", "Cleruchos"),
    "Kloster": ("Monastère", "Monastery", "Monastero", "Monasterio"),
    "Koch": ("Cuisinier", "Cook", "Cuoco", "Cocinero"),
    "Kodex": ("Codex", "Codex", "Codice", "Códice"),
    "Komarch": ("Comarque", "Comarch", "Comarca", "Comarca"),
    "Komarchen": ("Comarques", "Comarchs", "Comarchi", "Comarcas"),
    "Komogrammateus": ("Komogrammateus", "Komogrammateus", "Komogrammateus", "Komogrammateus"),
    "Kompromiß": ("Compromis", "Compromise", "Compromesso", "Compromiso"),
    "König": ("Roi", "King", "Re", "Rey"),
    "königlich": ("royal", "royal", "regio", "real"),
    "königlicher Schreiber": ("scribe royal", "royal scribe", "scriba regio", "escriba real"),
    "Königsland": ("Terre royale", "Royal land", "Terra regia", "Tierra real"),
    "Konto": ("Compte", "Account", "Conto", "Cuenta"),
    "Kopfsteuer": ("Capitation", "Poll tax", "Capitazione", "Capitación"),
    "Kopie": ("Copie", "Copy", "Copia", "Copia"),
    "Kopien": ("Copies", "Copies", "Copie", "Copias"),
    "koptisch": ("copte", "Coptic", "copto", "copto"),
    "Korb": ("Panier", "Basket", "Cesto", "Cesta"),
    "Korn": ("Grain", "Grain", "Grano", "Grano"),
    "Körperverletzung": ("Coups et blessures", "Bodily injury", "Lesioni personali", "Lesiones"),
    "Korrespondenz": ("Correspondance", "Correspondence", "Corrispondenza", "Correspondencia"),
    "Korrespondenz (amtlich) des Dioiketen Septimius Arrianus": ("Correspondance (officielle) du dioecète Septimius Arrianus", "Correspondence (official) of the Dioicetes Septimius Arrianus", "Corrispondenza (ufficiale) del dieceto Settimio Arriano", "Correspondencia (oficial) del dioiketes Septimio Arriano"),
    "Kosten": ("Frais", "Costs", "Spese", "Costes"),
    "Kranke": ("Malades", "Sick people", "Malati", "Enfermos"),
    "Krankheit": ("Maladie", "Illness", "Malattia", "Enfermedad"),
    "Kraut": ("Herbe", "Herb", "Erba", "Hierba"),
    "Kredit": ("Crédit", "Credit", "Credito", "Crédito"),
    "Krüge": ("Cruches", "Jugs", "Brocche", "Jarras"),
    "Kult": ("Culte", "Cult", "Culto", "Culto"),
    "Kündigung": ("Résiliation", "Termination", "Risoluzione", "Rescisión"),
    "Kurrah ben Sharik an den Pagarchen Basileios": ("Kurrah ben Sharik au pagarque Basileios", "Kurrah ben Sharik to the pagarch Basileios", "Kurrah ben Sharik al pagarca Basileio", "Kurrah ben Sharik al pagarca Basileios"),
    "Kyria - Klausel": ("Clause kyria", "Kyria clause", "Clausola kyria", "Cláusula kyria"),
    "Ladung": ("Chargement", "Cargo", "Carico", "Carga"),
    "Lage": ("Situation", "Location", "Situazione", "Ubicación"),
    "Lagebeschreibung": ("Description du terrain", "Description of location", "Descrizione del terreno", "Descripción del terreno"),
    "Land": ("Terre", "Land", "Terra", "Tierra"),
    "Landbesitz": ("Propriété foncière", "Land ownership", "Proprietà fondiaria", "Propiedad de la tierra"),
    "Ländereien": ("Terres", "Lands", "Terre", "Tierras"),
    "Landgut": ("Domaine", "Estate", "Tenuta", "Hacienda"),
    "Landvermessungssteuer": ("Impôt d'arpentage", "Land survey tax", "Tassa di misurazione fondiaria", "Impuesto de mensura"),
    "Landwirtschaft": ("Agriculture", "Agriculture", "Agricoltura", "Agricultura"),
    "landwirtschaftliche Arbeiten": ("travaux agricoles", "agricultural work", "lavori agricoli", "trabajos agrícolas"),
    "laographia": ("laographia", "laographia", "laographia", "laographia"),
    "Lashane": ("Lashane", "Lashane", "Lashane", "Lashane"),
    "Lebensmittel": ("Vivres", "Foodstuffs", "Generi alimentari", "Víveres"),
    "Legion": ("Légion", "Legion", "Legione", "Legión"),
    "Lehre": ("Apprentissage", "Apprenticeship", "Apprendistato", "Aprendizaje"),
    "Leinen": ("Lin", "Linen", "Lino", "Lino"),
    "Lettre": ("Lettre", "Letter", "Lettera", "Carta"),
    "Lettre de salutation": ("Lettre de salutation", "Greeting letter", "Lettera di saluto", "Carta de saludo"),
    "Lettres de l’alphabet et mots épars": ("Lettres de l’alphabet et mots épars", "Alphabet letters and scattered words", "Lettere dell'alfabeto e parole sparse", "Letras del alfabeto y palabras dispersas"),
    "Libellus": ("Libellus", "Libellus", "Libellus", "Libellus"),
    "Lieferung": ("Livraison", "Delivery", "Consegna", "Entrega"),
    "Lieferung (Wasser?) an Steinbrüche": ("Livraison (d'eau?) aux carrières", "Delivery (of water?) to quarries", "Consegna (d'acqua?) alle cave", "Entrega (de agua?) a las canteras"),
    "Lieferungen": ("Livraisons", "Deliveries", "Consegne", "Entregas"),
    "Lieferungskauf": ("Vente à livrer", "Forward sale", "Vendita a consegna", "Compraventa con entrega futura"),
    "Lin": ("Lin", "Flax", "Lino", "Lino"),
    "Linsen": ("Lentilles", "Lentils", "Lenticchie", "Lentejas"),
    "Liquidationsgesuch": ("Demande de liquidation", "Liquidation request", "Richiesta di liquidazione", "Solicitud de liquidación"),
    "Liste": ("Liste", "List", "Lista", "Lista"),
    "Listen": ("Listes", "Lists", "Liste", "Listas"),
    "Litrai": ("Litrai", "Litrai", "Litrai", "Litrai"),
    "Liturgen": ("Liturges", "Liturgists", "Liturghi", "Liturgos"),
    "Liturgie": ("Liturgie", "Liturgy", "Liturgia", "Liturgia"),
    "Liturgien": ("Liturgies", "Liturgies", "Liturgie", "Liturgias"),
    "Livre": ("Livre", "Book", "Libro", "Libro"),
    "Logistes": ("Logistès", "Logistes", "Logista", "Logista"),
    "Lohn": ("Salaire", "Wage", "Salario", "Salario"),
    "Lohnarbeit": ("Travail salarié", "Wage labour", "Lavoro salariato", "Trabajo asalariado"),
    "Löhne": ("Salaires", "Wages", "Salari", "Salarios"),
    "Lohnquittung": ("Quittance de salaire", "Wage receipt", "Ricevuta di salario", "Recibo de salario"),
    "Magie": ("Magie", "Magic", "Magia", "Magia"),
    "Mahnung": ("Rappel", "Reminder", "Sollecito", "Recordatorio"),
    "Maladie": ("Maladie", "Illness", "Malattia", "Enfermedad"),
    "Manichäisch": ("manichéen", "Manichaean", "manicheo", "maniqueo"),
    "Mantel": ("Manteau", "Cloak", "Mantello", "Manto"),
    "Maße": ("Mesures", "Measures", "Misure", "Medidas"),
    "Material": ("Matériel", "Material", "Materiale", "Material"),
    "Mathematik": ("Mathématiques", "Mathematics", "Matematica", "Matemáticas"),
    "Matrosen": ("Marins", "Sailors", "Marinai", "Marineros"),
    "Medizin": ("Médecine", "Medicine", "Medicina", "Medicina"),
    "Mehl": ("Farine", "Flour", "Farina", "Harina"),
    "Meldung": ("Déclaration", "Report", "Comunicazione", "Notificación"),
    "Memorandum": ("Mémorandum", "Memorandum", "Memorandum", "Memorándum"),
    "Menches": ("Menchès", "Menches", "Menches", "Menches"),
    "Mengen": ("Quantités", "Quantities", "Quantità", "Cantidades"),
    "merismos": ("merismos", "merismos", "merismos", "merismos"),
    "Messung": ("Mesure", "Measurement", "Misurazione", "Medición"),
    "Metallurgie": ("Métallurgie", "Metallurgy", "Metallurgia", "Metalurgia"),
    "Miete": ("Loyer", "Rent", "Affitto", "Alquiler"),
    "Mietzins": ("Loyer", "Rent", "Canone d'affitto", "Alquiler"),
    "Militär": ("Militaire", "Military", "Militare", "Militar"),
    "Mißhandlung": ("Mauvais traitements", "Ill-treatment", "Maltrattamento", "Maltrato"),
    "Mitgift": ("Dot", "Dowry", "Dote", "Dote"),
    "Mitteilung": ("Communication", "Notification", "Comunicazione", "Comunicación"),
    "Möbel": ("Meubles", "Furniture", "Mobili", "Muebles"),
    "Monat": ("Mois", "Month", "Mese", "Mes"),
    "Monate": ("Mois", "Months", "Mesi", "Meses"),
    "monatlich": ("mensuel", "monthly", "mensile", "mensual"),
    "Monatsnamen": ("Noms de mois", "Month names", "Nomi dei mesi", "Nombres de los meses"),
    "Mönch": ("Moine", "Monk", "Monaco", "Monje"),
    "Mönche": ("Moines", "Monks", "Monaci", "Monjes"),
    "Monopol": ("Monopole", "Monopoly", "Monopolio", "Monopolio"),
    "Mord": ("Meurtre", "Murder", "Omicidio", "Asesinato"),
    "Mühle": ("Moulin", "Mill", "Mulino", "Molino"),
    "Müller": ("Meunier", "Miller", "Mugnaio", "Molinero"),
    "Mumien (Ibis und Falken)": ("Momies (ibis et faucons)", "Mummies (ibises and falcons)", "Mummie (ibis e falchi)", "Momias (ibis y halcones)"),
    "Mumienetikett": ("Étiquette de momie", "Mummy label", "Etichetta di mummia", "Etiqueta de momia"),
    "Mumientäfelchen": ("Tablette de momie", "Mummy tablet", "Tavoletta di mummia", "Tablilla de momia"),
    "Mumientikett": ("Étiquette de momie", "Mummy label", "Etichetta di mummia", "Etiqueta de momia"),
    "N.N. an N.N.": ("N.N. à N.N.", "N.N. to N.N.", "N.N. a N.N.", "N.N. a N.N."),
    "Nachricht": ("Message", "Message", "Messaggio", "Mensaje"),
    "Nachtwache": ("Garde de nuit", "Night watch", "Guardia notturna", "Guardia nocturna"),
    "Nägel": ("Clous", "Nails", "Chiodi", "Clavos"),
    "Nahrung": ("Nourriture", "Food", "Cibo", "Alimento"),
    "Nahrungsmittel": ("Aliments", "Foodstuffs", "Alimenti", "Alimentos"),
    "Name": ("Nom", "Name", "Nome", "Nombre"),
    "Name und Vatersname": ("Nom et patronyme", "Name and patronymic", "Nome e patronimico", "Nombre y patronímico"),
    "Namen": ("Noms", "Names", "Nomi", "Nombres"),
    "Namen der Boten": ("Noms des messagers", "Names of messengers", "Nomi dei messaggeri", "Nombres de los mensajeros"),
    "Namenliste": ("Liste de noms", "List of names", "Elenco di nomi", "Lista de nombres"),
    "Naturalien": ("Produits en nature", "Goods in kind", "Beni in natura", "Bienes en especie"),
    "Naubion": ("Naubion", "Naubion", "Naubion", "Naubion"),
    "Naukleros": ("Naukleros", "Naukleros", "Naukleros", "Naukleros"),
    "Nestnephis": ("Nestnephis", "Nestnephis", "Nestnephis", "Nestnephis"),
    "nicht näher bestimmbar": ("non précisable", "not further determinable", "non meglio precisabile", "no especificable"),
    "Nikon an Zenon": ("Nikon à Zénon", "Nikon to Zeno", "Nikon a Zenone", "Nikon a Zenón"),
    "Nil": ("Nil", "Nile", "Nilo", "Nilo"),
    "NN an Apollonios": ("NN à Apollonios", "NN to Apollonius", "NN a Apollonio", "NN a Apolonio"),
    "NN an den König": ("NN au roi", "NN to the king", "NN al re", "NN al rey"),
    "NN an Herakleides": ("NN à Héraclide", "NN to Heraclides", "NN a Eraclide", "NN a Heráclides"),
    "NN an NN": ("NN à NN", "NN to NN", "NN a NN", "NN a NN"),
    "NN an Zenon": ("NN à Zénon", "NN to Zeno", "NN a Zenone", "NN a Zenón"),
    "Nomarch": ("Nomarque", "Nomarch", "Nomarca", "Nomarca"),
    "Notar": ("Notaire", "Notary", "Notaio", "Notario"),
    "Notariat": ("Notariat", "Notarial office", "Notariato", "Notaría"),
    "Notarsunterschrift": ("Signature du notaire", "Notary's signature", "Firma del notaio", "Firma del notario"),
    "Notarunterschrift": ("Signature du notaire", "Notary's signature", "Firma del notaio", "Firma del notario"),
    "Notiz": ("Note", "Note", "Nota", "Nota"),
    "Notiz über Zahlung von Geld": ("Note sur paiement d'argent", "Note on payment of money", "Nota su pagamento di denaro", "Nota sobre pago de dinero"),
    "Notizen": ("Notes", "Notes", "Note", "Notas"),
    "Obst": ("Fruits", "Fruit", "Frutta", "Fruta"),
    "Obstgarten": ("Verger", "Orchard", "Frutteto", "Huerto"),
    "Oikonomos": ("Oikonomos", "Oikonomos", "Oikonomos", "Oikonomos"),
    "Öl": ("Huile", "Oil", "Olio", "Aceite"),
    "Ölhersteller": ("Producteur d'huile", "Oil producer", "Produttore d'olio", "Productor de aceite"),
    "Oliven": ("Olives", "Olives", "Olive", "Aceitunas"),
    "Olivenöl": ("Huile d'olive", "Olive oil", "Olio d'oliva", "Aceite de oliva"),
    "Ölmühle": ("Moulin à huile", "Oil mill", "Frantoio", "Almazara"),
    "Opfer": ("Sacrifice", "Sacrifice", "Sacrificio", "Sacrificio"),
    "Orakel": ("Oracle", "Oracle", "Oracolo", "Oráculo"),
    "Ordre de transport «shiné nsa»": ("Ordre de transport «shiné nsa»", "Transport order «shiné nsa»", "Ordine di trasporto «shiné nsa»", "Orden de transporte «shiné nsa»"),
    "Orte": ("Lieux", "Places", "Luoghi", "Lugares"),
    "Ortschaften": ("Localités", "Localities", "Località", "Localidades"),
    "Ortsname": ("Toponyme", "Place name", "Toponimo", "Topónimo"),
    "Ortsnamen": ("Toponymes", "Place names", "Toponimi", "Topónimos"),
    "Pacht": ("Bail", "Lease", "Affitto", "Arrendamiento"),
    "Pächter": ("Fermier", "Tenant", "Affittuario", "Arrendatario"),
    "Pachtzins": ("Loyer foncier", "Rent", "Canone d'affitto", "Renta de arrendamiento"),
    "Pagarch": ("Pagarque", "Pagarch", "Pagarca", "Pagarca"),
    "Pain": ("Pain", "Bread", "Pane", "Pan"),
    "Palmen": ("Palmiers", "Palms", "Palme", "Palmeras"),
    "Palmenhain": ("Palmeraie", "Palm grove", "Palmeto", "Palmeral"),
    "Papyrus": ("Papyrus", "Papyrus", "Papiro", "Papiro"),
    "Parachoresis": ("Parachorèse", "Parachoresis", "Paracoresi", "Paracoresis"),
    "Paramone": ("Paramonè", "Paramone", "Paramone", "Paramone"),
    "Paratheke": ("Parathèkè", "Paratheke", "Paratheke", "Paratheke"),
    "Passierschein": ("Laissez-passer", "Pass", "Lasciapassare", "Salvoconducto"),
    "Pech": ("Poix", "Pitch", "Pece", "Pez"),
    "Penthemeros": ("Penthémèros", "Penthemeros", "Penthemeros", "Penthemeros"),
    "Penthemeros - Quittung": ("Quittance pentheméros", "Penthemeros receipt", "Ricevuta pentheméros", "Recibo penthemeros"),
    "Personen": ("Personnes", "Persons", "Persone", "Personas"),
    "Personenbeschreibung": ("Description de personne", "Description of person", "Descrizione di persona", "Descripción de persona"),
    "Petition": ("Pétition", "Petition", "Petizione", "Petición"),
    "Pfand": ("Gage", "Pledge", "Pegno", "Prenda"),
    "Pfändung": ("Saisie", "Distraint", "Pignoramento", "Embargo"),
    "Pferd": ("Cheval", "Horse", "Cavallo", "Caballo"),
    "Pferde": ("Chevaux", "Horses", "Cavalli", "Caballos"),
    "Pflanzen": ("Plantes", "Plants", "Piante", "Plantas"),
    "Philinos an Zenon": ("Philinos à Zénon", "Philinus to Zeno", "Filino a Zenone", "Filino a Zenón"),
    "Philokles an Kapparis": ("Philoklès à Kapparis", "Philokles to Kapparis", "Filocle a Kapparis", "Filocles a Kapparis"),
    "Plan": ("Plan", "Plan", "Piano", "Plan"),
    "Polizei": ("Police", "Police", "Polizia", "Policía"),
    "Post": ("Poste", "Post", "Posta", "Correo"),
    "praefectus Aegypti": ("praefectus Aegypti", "praefectus Aegypti", "praefectus Aegypti", "praefectus Aegypti"),
    "Präfekt": ("Préfet", "Prefect", "Prefetto", "Prefecto"),
    "praktor": ("praktor", "praktor", "praktor", "praktor"),
    "Praktores": ("Praktores", "Praktores", "Praktores", "Praktores"),
    "Präskript": ("Préscript", "Prescript", "Prescript", "Prescript"),
    "Preis": ("Prix", "Price", "Prezzo", "Precio"),
    "Preise": ("Prix", "Prices", "Prezzi", "Precios"),
    "Priester": ("Prêtre", "Priest", "Sacerdote", "Sacerdote"),
    "privat": ("privé", "private", "privato", "privado"),
    "Privilegien": ("Privilèges", "Privileges", "Privilegi", "Privilegios"),
    "Programm": ("Programme", "Programme", "Programma", "Programa"),
    "Pronoetes": ("Pronoètes", "Pronoetes", "Pronoetes", "Pronoetes"),
    "Prosangelma": ("Prosangelma", "Prosangelma", "Prosangelma", "Prosangelma"),
    "Proskynema": ("Proskynèma", "Proskynema", "Proskynema", "Proskynema"),
    "Prostagma": ("Prostagma", "Prostagma", "Prostagma", "Prostagma"),
    "Protokoll": ("Protocole", "Protocol", "Protocollo", "Protocolo"),
    "Protokoll (griechisch) und Unterschrift": ("Protocole (grec) et signature", "Protocol (Greek) and signature", "Protocollo (greco) e firma", "Protocolo (griego) y firma"),
    "Prozeß": ("Procès", "Trial", "Processo", "Proceso"),
    "Prügel": ("Coups", "Beating", "Percosse", "Golpes"),
    "Quittung": ("Quittance", "Receipt", "Ricevuta", "Recibo"),
    "Quittung oder Notiz": ("Quittance ou note", "Receipt or note", "Ricevuta o nota", "Recibo o nota"),
    "Quittungen": ("Quittances", "Receipts", "Ricevute", "Recibos"),
    "Quittungsbogen": ("Feuille de quittances", "Receipt sheet", "Foglio di ricevute", "Hoja de recibos"),
    "Rat": ("Conseil", "Council", "Consiglio", "Consejo"),
    "Ration": ("Ration", "Ration", "Razione", "Ración"),
    "Rationen": ("Rations", "Rations", "Razioni", "Raciones"),
    "Raub": ("Vol", "Robbery", "Rapina", "Robo"),
    "Rechnung": ("Compte", "Account", "Conto", "Cuenta"),
    "Rechnungen": ("Comptes", "Accounts", "Conti", "Cuentas"),
    "Rechte": ("Droits", "Rights", "Diritti", "Derechos"),
    "Rechtsangelegenheit": ("Affaire juridique", "Legal matter", "Questione giuridica", "Asunto jurídico"),
    "Rechtsstreit": ("Litige", "Lawsuit", "Controversia", "Litigio"),
    "Regelung": ("Règlement", "Settlement", "Regolamento", "Reglamento"),
    "Regelungen": ("Règlements", "Settlements", "Regolamenti", "Reglamentos"),
    "Register": ("Registre", "Register", "Registro", "Registro"),
    "Registrierung": ("Enregistrement", "Registration", "Registrazione", "Registro"),
    "Reise": ("Voyage", "Journey", "Viaggio", "Viaje"),
    "Reisen": ("Voyages", "Journeys", "Viaggi", "Viajes"),
    "Reiter": ("Cavalier", "Horseman", "Cavaliere", "Jinete"),
    "Religion": ("Religion", "Religion", "Religione", "Religión"),
    "Rennen": ("Course", "Race", "Corsa", "Carrera"),
    "Reparatur": ("Réparation", "Repair", "Riparazione", "Reparación"),
    "Requisitionen": ("Réquisitions", "Requisitions", "Requisizioni", "Requisas"),
    "Reskript": ("Rescrit", "Rescript", "Rescritto", "Rescripto"),
    "Rettich": ("Radis", "Radish", "Ravanello", "Rábano"),
    "Rezept": ("Recette", "Recipe", "Ricetta", "Receta"),
    "Rezepte": ("Recettes", "Recipes", "Ricette", "Recetas"),
    "Rinder": ("Bovins", "Cattle", "Bovini", "Ganado bovino"),
    "Rizinus": ("Ricin", "Castor", "Ricino", "Ricino"),
    "Rohr": ("Roseau", "Reed", "Canna", "Caña"),
    "Rolle": ("Rouleau", "Roll", "Rotolo", "Rollo"),
    "römische Zahlen": ("chiffres romains", "Roman numerals", "numeri romani", "números romanos"),
    "Rückgabe": ("Restitution", "Return", "Restituzione", "Devolución"),
    "Rückstand": ("Arriéré", "Arrears", "Arretrato", "Atraso"),
    "Rückstände": ("Arriérés", "Arrears", "Arretrati", "Atrasos"),
    "Rückzahlung": ("Remboursement", "Repayment", "Rimborso", "Reembolso"),
    "Rückzahlung eines Darlehens": ("Remboursement d'un prêt", "Repayment of a loan", "Rimborso di un prestito", "Reembolso de un préstamo"),
    "Saat": ("Semence", "Seed", "Semente", "Semilla"),
    "Saatgut": ("Semence", "Seed", "Sementi", "Semilla"),
    "Säcke": ("Sacs", "Sacks", "Sacchi", "Sacos"),
    "Salaisons": ("Salaisons", "Salted goods", "Salumi", "Salazones"),
    "Salbe": ("Onguent", "Ointment", "Unguento", "Ungüento"),
    "Salz": ("Sel", "Salt", "Sale", "Sal"),
    "Salzsteuer": ("Impôt sur le sel", "Salt tax", "Tassa sul sale", "Impuesto sobre la sal"),
    "Samen": ("Semence", "Seed", "Semente", "Semilla"),
    "Sammelquittung": ("Quittance collective", "Collective receipt", "Ricevuta collettiva", "Recibo colectivo"),
    "Sammlung": ("Collection", "Collection", "Collezione", "Colección"),
    "Schaden": ("Dommage", "Damage", "Danno", "Daño"),
    "Schafe": ("Moutons", "Sheep", "Pecore", "Ovejas"),
    "Schätzung": ("Estimation", "Estimate", "Stima", "Estimación"),
    "Scheidung": ("Divorce", "Divorce", "Divorzio", "Divorcio"),
    "Schenkung": ("Donation", "Donation", "Donazione", "Donación"),
    "Schenkung (Testament) auf den Todesfall": ("Donation (testament) à cause de mort", "Gift (testament) on death", "Donazione (testamento) a causa di morte", "Donación (testamento) por causa de muerte"),
    "Schenkung eines Kindes an ein Kloster": ("Donation d'un enfant à un monastère", "Donation of a child to a monastery", "Donazione di un bambino a un monastero", "Donación de un niño a un monasterio"),
    "Schiff": ("Bateau", "Ship", "Nave", "Barco"),
    "Schiffbau": ("Construction navale", "Shipbuilding", "Costruzione navale", "Construcción naval"),
    "Schiffe": ("Bateaux", "Ships", "Navi", "Barcos"),
    "Schiffer": ("Marinier", "Boatman", "Battelliere", "Barquero"),
    "Schiffsbau": ("Construction navale", "Shipbuilding", "Costruzione navale", "Construcción naval"),
    "Schlichtung": ("Conciliation", "Arbitration", "Conciliazione", "Conciliación"),
    "Schluß": ("Conclusion", "Conclusion", "Conclusione", "Conclusión"),
    "Schmied": ("Forgeron", "Smith", "Fabbro", "Herrero"),
    "Schmuck": ("Bijoux", "Jewellery", "Gioielli", "Joyas"),
    "Schreiben": ("Lettre", "Letter", "Lettera", "Carta"),
    "Schreiber": ("Scribe", "Scribe", "Scriba", "Escriba"),
    "Schreibübung": ("Exercice d'écriture", "Writing exercise", "Esercizio di scrittura", "Ejercicio de escritura"),
    "Schreibübungen": ("Exercices d'écriture", "Writing exercises", "Esercizi di scrittura", "Ejercicios de escritura"),
    "Schriftverkehr": ("Correspondance", "Correspondence", "Corrispondenza", "Correspondencia"),
    "Schuld": ("Dette", "Debt", "Debito", "Deuda"),
    "Schulden": ("Dettes", "Debts", "Debiti", "Deudas"),
    "Schuldner": ("Débiteur", "Debtor", "Debitore", "Deudor"),
    "Schuldschein": ("Reconnaissance de dette", "Promissory note", "Pagherò", "Pagaré"),
    "Schuldschein oder Quittung": ("Reconnaissance de dette ou quittance", "Promissory note or receipt", "Pagherò o ricevuta", "Pagaré o recibo"),
    "Schultext": ("Texte scolaire", "School text", "Testo scolastico", "Texto escolar"),
    "Schutz": ("Protection", "Protection", "Protezione", "Protección"),
    "Schutzbriefe": ("Lettres de protection", "Letters of protection", "Lettere di protezione", "Cartas de protección"),
    "Schwein": ("Porc", "Pig", "Maiale", "Cerdo"),
    "Schweine": ("Porcs", "Pigs", "Maiali", "Cerdos"),
    "Schwierigkeiten": ("Difficultés", "Difficulties", "Difficoltà", "Dificultades"),
    "Scribe": ("Scribe", "Scribe", "Scriba", "Escriba"),
    "Seeleute": ("Marins", "Sailors", "Marinai", "Marineros"),
    "Seil": ("Corde", "Rope", "Corda", "Cuerda"),
    "Seile": ("Cordes", "Ropes", "Corde", "Cuerdas"),
    "Sendung": ("Envoi", "Shipment", "Invio", "Envío"),
    "Sendung von Geld": ("Envoi d'argent", "Sending of money", "Invio di denaro", "Envío de dinero"),
    "Sesam": ("Sésame", "Sesame", "Sesamo", "Sésamo"),
    "Sicherheit": ("Sûreté", "Security", "Sicurezza", "Seguridad"),
    "Siegel": ("Sceau", "Seal", "Sigillo", "Sello"),
    "Signalement": ("Signalement", "Description", "Connotati", "Filiación"),
    "Silber": ("Argent", "Silver", "Argento", "Plata"),
    "Sitologe": ("Sitologue", "Sitologos", "Sitologo", "Sitólogo"),
    "Sitologen": ("Sitologues", "Sitologoi", "Sitologi", "Sitólogos"),
    "Sklave": ("Esclave", "Slave", "Schiavo", "Esclavo"),
    "Sklaven": ("Esclaves", "Slaves", "Schiavi", "Esclavos"),
    "Sklavin": ("Esclave", "Female slave", "Schiava", "Esclava"),
    "Sohn": ("Fils", "Son", "Figlio", "Hijo"),
    "Sold": ("Solde", "Pay", "Soldo", "Paga"),
    "Soldat": ("Soldat", "Soldier", "Soldato", "Soldado"),
    "Soldat an cibariator": ("Soldat au cibariator", "Soldier to cibariator", "Soldato al cibariator", "Soldado al cibariator"),
    "Soldaten": ("Soldats", "Soldiers", "Soldati", "Soldados"),
    "Speicher": ("Grenier", "Granary", "Granaio", "Granero"),
    "Speicherquittung": ("Quittance de grenier", "Granary receipt", "Ricevuta di granaio", "Recibo de granero"),
    "Spezialisten": ("Spécialistes", "Specialists", "Specialisti", "Especialistas"),
    "Sporteln": ("Sportules", "Sportulae", "Sportule", "Espórtulas"),
    "Spreu": ("Balle", "Chaff", "Pula", "Paja"),
    "Staat": ("État", "State", "Stato", "Estado"),
    "Staatsland": ("Terre d'État", "State land", "Terra demaniale", "Tierra del Estado"),
    "Stall": ("Étable", "Stable", "Stalla", "Establo"),
    "Steckbrief": ("Avis de recherche", "Wanted notice", "Avviso di ricerca", "Orden de busca"),
    "Steinbruch": ("Carrière", "Quarry", "Cava", "Cantera"),
    "Steine": ("Pierres", "Stones", "Pietre", "Piedras"),
    "Steinmetz": ("Tailleur de pierre", "Stonemason", "Scalpellino", "Cantero"),
    "Stellung": ("Position", "Position", "Posizione", "Posición"),
    "Stellvertreter": ("Représentant", "Representative", "Rappresentante", "Representante"),
    "Stellvertretung": ("Représentation", "Representation", "Rappresentanza", "Representación"),
    "Steuereinnehmer": ("Percepteur", "Tax collector", "Esattore", "Recaudador"),
    "Steuern": ("Impôts", "Taxes", "Imposte", "Impuestos"),
    "Steuerpächter": ("Fermier des impôts", "Tax farmer", "Appaltatore di imposte", "Arrendatario de impuestos"),
    "Steuerzahler": ("Contribuable", "Taxpayer", "Contribuente", "Contribuyente"),
    "Stoff": ("Étoffe", "Fabric", "Tessuto", "Tela"),
    "Strafe": ("Peine", "Penalty", "Pena", "Pena"),
    "Stratege": ("Stratège", "Strategos", "Stratego", "Estratega"),
    "strategos": ("strategos", "strategos", "strategos", "strategos"),
    "Streit": ("Querelle", "Dispute", "Lite", "Disputa"),
    "Stroh": ("Paille", "Straw", "Paglia", "Paja"),
    "Subskription": ("Souscription", "Subscription", "Sottoscrizione", "Suscripción"),
    "Symmachos": ("Symmachos", "Symmachos", "Symmachos", "Symmachos"),
    "Syntaximon": ("Syntaximon", "Syntaximon", "Syntaximon", "Syntaximon"),
    "Syros an Heroninos": ("Syros à Héroninos", "Syros to Heroninus", "Syros a Heroninos", "Syros a Heronino"),
    "Tabelle": ("Tableau", "Table", "Tabella", "Tabla"),
    "Tachygraphie": ("Tachygraphie", "Tachygraphy", "Tachigrafia", "Taquigrafía"),
    "Tag": ("Jour", "Day", "Giorno", "Día"),
    "Tage": ("Jours", "Days", "Giorni", "Días"),
    "Tagebuch": ("Journal", "Diary", "Diario", "Diario"),
    "Tagebuch einer Poststation (Fragment)": ("Journal d'une station postale (fragment)", "Diary of a postal station (fragment)", "Diario di una stazione postale (frammento)", "Diario de una estación postal (fragmento)"),
    "Tagesdaten": ("Dates journalières", "Daily dates", "Date giornaliere", "Fechas diarias"),
    "Taubenschlag": ("Pigeonnier", "Dovecote", "Colombaia", "Palomar"),
    "Tausch": ("Échange", "Exchange", "Scambio", "Intercambio"),
    "Teil": ("Partie", "Part", "Parte", "Parte"),
    "Teile": ("Parties", "Parts", "Parti", "Partes"),
    "Teilpacht": ("Métayage", "Sharecropping", "Mezzadria", "Aparcería"),
    "Teilung": ("Partage", "Division", "Divisione", "División"),
    "Tempel": ("Temple", "Temple", "Tempio", "Templo"),
    "Tenne": ("Aire de battage", "Threshing floor", "Aia", "Era"),
    "tessera": ("tessera", "tessera", "tessera", "tessera"),
    "Testament": ("Testament", "Testament", "Testamento", "Testamento"),
    "Testamente": ("Testaments", "Testaments", "Testamenti", "Testamentos"),
    "Textile": ("Textile", "Textile", "Tessile", "Textil"),
    "Textiles": ("Textiles", "Textiles", "Tessili", "Textiles"),
    "Textilien": ("Textiles", "Textiles", "Tessili", "Textiles"),
    "Tier": ("Animal", "Animal", "Animale", "Animal"),
    "Tiere": ("Animaux", "Animals", "Animali", "Animales"),
    "Tilgung": ("Amortissement", "Repayment", "Estinzione", "Amortización"),
    "Titulatur": ("Titulature", "Titulature", "Titolatura", "Titulatura"),
    "Tochter": ("Fille", "Daughter", "Figlia", "Hija"),
    "Tod": ("Mort", "Death", "Morte", "Muerte"),
    "Todesfall": ("Décès", "Death", "Decesso", "Defunción"),
    "tomos synkollesimos": ("tomos synkollesimos", "tomos synkollesimos", "tomos synkollesimos", "tomos synkollesimos"),
    "Tonkrug": ("Cruche en terre", "Earthenware jug", "Brocca di terracotta", "Cántaro de barro"),
    "Töpfer": ("Potier", "Potter", "Vasaio", "Alfarero"),
    "Töpferei": ("Poterie", "Pottery", "Ceramica", "Alfarería"),
    "Torzoll": ("Taxe de passage", "Gate toll", "Pedaggio", "Portazgo"),
    "Transport": ("Transport", "Transport", "Trasporto", "Transporte"),
    "Transport auf Eseln": ("Transport à dos d'âne", "Transport by donkey", "Trasporto su asini", "Transporte en burros"),
    "Transport auf Kamelen": ("Transport à dos de chameau", "Transport by camel", "Trasporto su cammelli", "Transporte en camellos"),
    "Trauben": ("Raisins", "Grapes", "Uva", "Uvas"),
    "Truppenversorgung": ("Approvisionnement des troupes", "Troop supply", "Approvvigionamento delle truppe", "Avituallamiento de tropas"),
    "turma": ("turma", "turma", "turma", "turma"),
    "Übereinkunft": ("Accord", "Agreement", "Accordo", "Acuerdo"),
    "Überfall": ("Agression", "Assault", "Aggressione", "Asalto"),
    "Übergabe": ("Remise", "Handover", "Consegna", "Entrega"),
    "Übernahme": ("Prise en charge", "Takeover", "Presa in carico", "Toma a cargo"),
    "Überprüfung": ("Vérification", "Verification", "Verifica", "Verificación"),
    "Übersicht": ("Aperçu", "Overview", "Quadro", "Resumen"),
    "Überstellung": ("Transfert", "Transfer", "Trasferimento", "Traslado"),
    "Übertragung": ("Transfert", "Transfer", "Trasferimento", "Transferencia"),
    "Überweisung": ("Virement", "Transfer", "Bonifico", "Transferencia"),
    "Überweisung von Getreidemengen": ("Virement de quantités de grain", "Transfer of quantities of grain", "Bonifico di quantità di grano", "Transferencia de cantidades de grano"),
    "Übung": ("Exercice", "Exercise", "Esercizio", "Ejercicio"),
    "Uhrzeit": ("Heure", "Time", "Ora", "Hora"),
    "Umlage": ("Répartition", "Apportionment", "Ripartizione", "Reparto"),
    "Umschreibung": ("Réécriture", "Transcription", "Trascrizione", "Transcripción"),
    "unbestimmbar": ("indéterminable", "indeterminable", "indeterminabile", "indeterminable"),
    "unbewässert": ("non irrigué", "unirrigated", "non irrigato", "sin riego"),
    "unbewässertes Land": ("terre non irriguée", "unirrigated land", "terra non irrigata", "tierra sin riego"),
    "Unterhalt": ("Entretien", "Maintenance", "Mantenimento", "Manutención"),
    "Unterschrift": ("Signature", "Signature", "Firma", "Firma"),
    "Unterschriften": ("Signatures", "Signatures", "Firme", "Firmas"),
    "Untersuchung": ("Enquête", "Investigation", "Indagine", "Investigación"),
    "Urkunde": ("Acte", "Deed", "Atto", "Escritura"),
    "Urteil": ("Jugement", "Judgement", "Sentenza", "Sentencia"),
    "Verein": ("Association", "Association", "Associazione", "Asociación"),
    "Vereinbarung": ("Convention", "Agreement", "Accordo", "Acuerdo"),
    "Verfügung": ("Disposition", "Disposition", "Disposizione", "Disposición"),
    "Vergleich": ("Compromis", "Settlement", "Transazione", "Acuerdo"),
    "Verhaftung": ("Arrestation", "Arrest", "Arresto", "Detención"),
    "Verhandlung": ("Audience", "Hearing", "Udienza", "Audiencia"),
    "Verkauf": ("Vente", "Sale", "Vendita", "Venta"),
    "Verladung": ("Chargement", "Loading", "Carico", "Carga"),
    "Verletzung": ("Blessure", "Injury", "Ferita", "Herida"),
    "Verlust": ("Perte", "Loss", "Perdita", "Pérdida"),
    "Vermerk": ("Note", "Note", "Annotazione", "Nota"),
    "Vermessung": ("Arpentage", "Survey", "Misurazione", "Mensura"),
    "Vermögen": ("Fortune", "Wealth", "Patrimonio", "Patrimonio"),
    "Verpflegung": ("Ravitaillement", "Provisioning", "Vettovagliamento", "Avituallamiento"),
    "Verpflichtung": ("Obligation", "Obligation", "Obbligo", "Obligación"),
    "Verpflichtung zum Transport nach Alexandria": ("Obligation de transport vers Alexandrie", "Obligation to transport to Alexandria", "Obbligo di trasporto ad Alessandria", "Obligación de transporte a Alejandría"),
    "verrichtete Arbeit": ("travail effectué", "work performed", "lavoro svolto", "trabajo realizado"),
    "Versorgung": ("Approvisionnement", "Supply", "Approvvigionamento", "Suministro"),
    "Versprechen": ("Promesse", "Promise", "Promessa", "Promesa"),
    "Versteigerung": ("Vente aux enchères", "Auction", "Asta", "Subasta"),
    "Verteilung": ("Distribution", "Distribution", "Distribuzione", "Distribución"),
    "Vertrag": ("Contrat", "Contract", "Contratto", "Contrato"),
    "Verträge": ("Contrats", "Contracts", "Contratti", "Contratos"),
    "Verwalter": ("Administrateur", "Administrator", "Amministratore", "Administrador"),
    "Verwaltung": ("Administration", "Administration", "Amministrazione", "Administración"),
    "Verzeichnis": ("Registre", "Register", "Registro", "Registro"),
    "Verzeichnis über Eingang und Weiterleitung von Briefen": ("Registre des lettres reçues et transmises", "Register of incoming and forwarded letters", "Registro delle lettere ricevute e inoltrate", "Registro de cartas recibidas y transmitidas"),
    "Verzicht": ("Renonciation", "Renunciation", "Rinuncia", "Renuncia"),
    "vestis militaris": ("vestis militaris", "vestis militaris", "vestis militaris", "vestis militaris"),
    "Veteran": ("Vétéran", "Veteran", "Veterano", "Veterano"),
    "Vieh": ("Bétail", "Livestock", "Bestiame", "Ganado"),
    "Vin": ("Vin", "Wine", "Vino", "Vino"),
    "Vögel": ("Oiseaux", "Birds", "Uccelli", "Aves"),
    "Vollmacht": ("Procuration", "Power of attorney", "Procura", "Poder"),
    "Vorauszahlung": ("Avance", "Advance payment", "Acconto", "Pago anticipado"),
    "Vorladung": ("Citation", "Summons", "Citazione", "Citación"),
    "Vormund": ("Tuteur", "Guardian", "Tutore", "Tutor"),
    "Vormundschaft": ("Tutelle", "Guardianship", "Tutela", "Tutela"),
    "Vorschlag": ("Proposition", "Proposal", "Proposta", "Propuesta"),
    "Voyage au nord": ("Voyage au nord", "Voyage to the north", "Viaggio a nord", "Viaje al norte"),
    "Wache": ("Garde", "Guard", "Guardia", "Guardia"),
    "Wächter": ("Gardien", "Watchman", "Custode", "Vigilante"),
    "Wagen": ("Char", "Wagon", "Carro", "Carro"),
    "Waise": ("Orphelin", "Orphan", "Orfano", "Huérfano"),
    "Waisen": ("Orphelins", "Orphans", "Orfani", "Huérfanos"),
    "Waren": ("Marchandises", "Goods", "Merci", "Mercancías"),
    "Wasser": ("Eau", "Water", "Acqua", "Agua"),
    "Wasserrad": ("Roue à eau", "Water wheel", "Ruota idraulica", "Noria"),
    "Weber": ("Tisserand", "Weaver", "Tessitore", "Tejedor"),
    "Weberei": ("Tissage", "Weaving", "Tessitura", "Tejido"),
    "Weide": ("Pâturage", "Pasture", "Pascolo", "Pastizal"),
    "Weihung": ("Consécration", "Dedication", "Consacrazione", "Consagración"),
    "Wein": ("Vin", "Wine", "Vino", "Vino"),
    "Weinbau": ("Viticulture", "Viticulture", "Viticoltura", "Viticultura"),
    "Weinberg": ("Vignoble", "Vineyard", "Vigneto", "Viñedo"),
    "Weingarten": ("Vigne", "Vineyard", "Vigna", "Viña"),
    "Weinland": ("Terre à vigne", "Vineyard land", "Terreno vitato", "Tierra de viña"),
    "Weinlese": ("Vendange", "Wine harvest", "Vendemmia", "Vendimia"),
    "Weizen": ("Blé", "Wheat", "Grano", "Trigo"),
    "Werg": ("Étoupe", "Tow", "Stoppa", "Estopa"),
    "Werkstatt": ("Atelier", "Workshop", "Officina", "Taller"),
    "Werkvertrag": ("Contrat d'entreprise", "Work contract", "Contratto d'opera", "Contrato de obra"),
    "Werkzeug": ("Outil", "Tool", "Utensile", "Herramienta"),
    "Werkzeuge": ("Outils", "Tools", "Utensili", "Herramientas"),
    "Wirtschaft": ("Économie", "Economy", "Economia", "Economía"),
    "Witwe": ("Veuve", "Widow", "Vedova", "Viuda"),
    "Wohnrecht": ("Droit d'habitation", "Right of residence", "Diritto di abitazione", "Derecho de habitación"),
    "Wohnung": ("Logement", "Dwelling", "Abitazione", "Vivienda"),
    "Wolle": ("Laine", "Wool", "Lana", "Lana"),
    "Zahl": ("Nombre", "Number", "Numero", "Número"),
    "Zahlen": ("Nombres", "Numbers", "Numeri", "Números"),
    "Zahlung": ("Paiement", "Payment", "Pagamento", "Pago"),
    "Zahlung eines Darlehens in Saatgut": ("Paiement d'un prêt en semence", "Payment of a loan in seed", "Pagamento di un prestito in sementi", "Pago de un préstamo en semilla"),
    "Zahlung von Geld": ("Paiement d'argent", "Payment of money", "Pagamento di denaro", "Pago de dinero"),
    "Zahlungen": ("Paiements", "Payments", "Pagamenti", "Pagos"),
    "Zahlungsanweisung": ("Ordre de paiement", "Payment order", "Ordine di pagamento", "Orden de pago"),
    "Zahlungsauftrag": ("Ordre de paiement", "Payment order", "Ordine di pagamento", "Orden de pago"),
    "Zauber": ("Sortilège", "Spell", "Incantesimo", "Hechizo"),
    "Zeichnung": ("Dessin", "Drawing", "Disegno", "Dibujo"),
    "Zensus": ("Recensement", "Census", "Censimento", "Censo"),
    "Zeuge": ("Témoin", "Witness", "Testimone", "Testigo"),
    "Zeugen": ("Témoins", "Witnesses", "Testimoni", "Testigos"),
    "Zeugenaussage": ("Témoignage", "Witness statement", "Testimonianza", "Testimonio"),
    "Ziegel": ("Brique", "Brick", "Mattone", "Ladrillo"),
    "Ziegen": ("Chèvres", "Goats", "Capre", "Cabras"),
    "Zimmer": ("Chambre", "Room", "Stanza", "Habitación"),
    "Zimmermann": ("Charpentier", "Carpenter", "Falegname", "Carpintero"),
    "Zins": ("Intérêt", "Interest", "Interesse", "Interés"),
    "Zinsen": ("Intérêts", "Interests", "Interessi", "Intereses"),
    "Zoll": ("Douane", "Customs", "Dogana", "Aduana"),
    "Zubehör": ("Accessoires", "Accessories", "Accessori", "Accesorios"),
    "Zucht": ("Élevage", "Breeding", "Allevamento", "Cría"),
    "Zusammenfassung": ("Résumé", "Summary", "Riassunto", "Resumen"),
    "Zusendung": ("Envoi", "Sending", "Invio", "Envío"),
    "Zuteilung": ("Attribution", "Allocation", "Assegnazione", "Asignación"),
    "zwei Exemplare": ("deux exemplaires", "two copies", "due esemplari", "dos ejemplares"),
    "zwei Kopien": ("deux copies", "two copies", "due copie", "dos copias"),
    "Zwillinge": ("Jumeaux", "Twins", "Gemelli", "Gemelos"),
}


def main() -> int:
    csv_path = Path(__file__).resolve().parent.parent / "data" / "keywords.csv"
    rows: list[list[str]] = []
    missing: list[str] = []

    with csv_path.open(encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        rows.append(header)
        # Expected header: category, origin, de, fr, en, es, it
        for row in reader:
            # Pad short rows to 7 columns just in case.
            while len(row) < 7:
                row.append("")
            de = row[2]
            tr = TRANSLATIONS.get(de)
            if tr is None:
                missing.append(de)
                rows.append(row)
                continue
            fr, en, it, es = tr
            if not row[3]:
                row[3] = fr
            if not row[4]:
                row[4] = en
            if not row[5]:
                row[5] = es
            if not row[6]:
                row[6] = it
            rows.append(row)

    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerows(rows)

    if missing:
        print(f"Missing translations for {len(missing)} keyword(s):", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 1
    print(f"Updated {csv_path} – {len(rows) - 1} rows.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
